PROG -> DECLS

DECLS -> DECL DECLS
DECLS ->

DECL -> TYPE_DECL
DECL -> PROC_DECL

TYPE_DECL -> KEYWORD_TYPE NEWLINE INDENT TYPE_DEFS DEDENT

TYPE_DEFS -> TYPE_DEF TYPE_DEFS
TYPE_DEFS ->

TYPE_DEF -> ID ASSIGN KEYWORD_OBJECT NEWLINE INDENT FIELD_DECLS DEDENT

FIELD_DECLS -> FIELD_DECL FIELD_DECLS
FIELD_DECLS ->

FIELD_DECL -> ID COLON TYPE_EXPR NEWLINE
FIELD_DECL -> ID COMMA ID_LIST COLON TYPE_EXPR NEWLINE

ID_LIST -> ID
ID_LIST -> ID COMMA ID_LIST

PROC_DECL -> KEYWORD_PROC ID LPAREN PARAMS RPAREN RET_TYPE ASSIGN NEWLINE INDENT STMTS DEDENT

RET_TYPE -> COLON TYPE_EXPR
RET_TYPE ->

PARAMS -> PARAM_LIST
PARAMS ->

PARAM_LIST -> PARAM
PARAM_LIST -> PARAM COMMA PARAM_LIST

PARAM -> ID COLON TYPE_EXPR

TYPE_EXPR -> SIMPLE_TYPE
TYPE_EXPR -> SEQ_TYPE
TYPE_EXPR -> ARRAY_TYPE
TYPE_EXPR -> ID

SIMPLE_TYPE -> KEYWORD_INT
SIMPLE_TYPE -> KEYWORD_FLOAT
SIMPLE_TYPE -> KEYWORD_BOOL
SIMPLE_TYPE -> KEYWORD_STRING

SEQ_TYPE -> KEYWORD_SEQ LBRACKET TYPE_EXPR RBRACKET
ARRAY_TYPE -> KEYWORD_ARRAY LBRACKET NUM_INT COMMA TYPE_EXPR RBRACKET

STMTS -> STMT STMTS
STMTS ->

STMT -> VAR_DECL NEWLINE
STMT -> ASSIGN_STMT NEWLINE
STMT -> RETURN_STMT NEWLINE
STMT -> IF_STMT
STMT -> WHILE_STMT
STMT -> EXPR NEWLINE

VAR_DECL -> KEYWORD_VAR ID COLON TYPE_EXPR
VAR_DECL -> KEYWORD_VAR ID COLON TYPE_EXPR ASSIGN EXPR

ASSIGN_STMT -> ACCESS ASSIGN EXPR

RETURN_STMT -> KEYWORD_RETURN EXPR
RETURN_STMT -> KEYWORD_RETURN

IF_STMT -> KEYWORD_IF EXPR COLON NEWLINE INDENT STMTS DEDENT ELIF_PART ELSE_PART

ELIF_PART -> KEYWORD_ELIF EXPR COLON NEWLINE INDENT STMTS DEDENT ELIF_PART
ELIF_PART ->

ELSE_PART -> KEYWORD_ELSE COLON NEWLINE INDENT STMTS DEDENT
ELSE_PART ->

WHILE_STMT -> KEYWORD_WHILE EXPR COLON NEWLINE INDENT STMTS DEDENT

EXPR -> OR_EXPR

OR_EXPR -> OR_EXPR KEYWORD_OR AND_EXPR
OR_EXPR -> AND_EXPR

AND_EXPR -> AND_EXPR KEYWORD_AND CMP_EXPR
AND_EXPR -> CMP_EXPR

CMP_EXPR -> CMP_EXPR LT ADD_EXPR
CMP_EXPR -> CMP_EXPR LE ADD_EXPR
CMP_EXPR -> CMP_EXPR GT ADD_EXPR
CMP_EXPR -> CMP_EXPR GE ADD_EXPR
CMP_EXPR -> CMP_EXPR EQ ADD_EXPR
CMP_EXPR -> CMP_EXPR NE ADD_EXPR
CMP_EXPR -> ADD_EXPR

ADD_EXPR -> ADD_EXPR PLUS MUL_EXPR
ADD_EXPR -> ADD_EXPR MINUS MUL_EXPR
ADD_EXPR -> MUL_EXPR

MUL_EXPR -> MUL_EXPR MULT UNARY_EXPR
MUL_EXPR -> MUL_EXPR DIV UNARY_EXPR
MUL_EXPR -> MUL_EXPR KEYWORD_MOD UNARY_EXPR
MUL_EXPR -> UNARY_EXPR

UNARY_EXPR -> MINUS UNARY_EXPR
UNARY_EXPR -> KEYWORD_NOT UNARY_EXPR
UNARY_EXPR -> POSTFIX_EXPR

POSTFIX_EXPR -> PRIMARY
POSTFIX_EXPR -> POSTFIX_EXPR LBRACKET EXPR RBRACKET
POSTFIX_EXPR -> POSTFIX_EXPR DOT ID
POSTFIX_EXPR -> POSTFIX_EXPR LPAREN ARGS RPAREN

PRIMARY -> NUM_INT
PRIMARY -> NUM_FLOAT
PRIMARY -> ID
PRIMARY -> LPAREN EXPR RPAREN

ARGS -> ARG_LIST
ARGS ->

ARG_LIST -> EXPR
ARG_LIST -> EXPR COMMA ARG_LIST

ACCESS -> ID
ACCESS -> ACCESS LBRACKET EXPR RBRACKET
ACCESS -> ACCESS DOT ID